require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'test/**/*.rb'
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Metrics/BlockLength:
  Max: 50

Layout/LineLength:
  Max: 160

Style/ClassAndModuleChildren:
  Enabled: false
