require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'test/**/*.rb'
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'config.ru'

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false
